document.getEelementById('#container')
document.getEelementById('#night-mode-on')
document.getEelementById('#night-mode-Container')
document.getEelementById('#password-Viewer')
document.getEelementById('#code-generator')